version: "3.9"
services:
    notesdb:
        image: 'postgres:latest'
        environment:
            POSTGRES_USER: admin 
            POSTGRES_PASSWORD: Admin
            POSTGRES_DB: notes 
        ports:
          - "5432:5432"
        extra_hosts:
          - "host.docker.internal:host-gateway"

    web:
        build: .
        ports:
          - "8000:80"
        depends_on:
          - notesdb
        extra_hosts:
          - "host.docker.internal:host-gateway"
    