version: "3.9"
services:
    notesdb:
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        environment:
            MSSQL_SA_PASSWORD: "MyPassword1234!"
            ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
#        volumes:
#          -  notesdb:/var/opt/mssql/data
    web:
        build: .
        ports:
          - "8000:80"
        depends_on:
          - notesdb
#volumes:
#  notesdb:
    