version: "3.9"
services:
    notesdb:
        image: 'postgres:latest'
        environment:
            POSTGRES_USER: admin 
            POSTGRES_PASSWORD: Admin
            POSTGRES_DB: notes 
        ports:
          - "6543:5432"
        extra_hosts:
          - "host.docker.internal:host-gateway"
#        volumes:
#          -  notesdb:/var/opt/mssql/data

    web:
        build: .
        ports:
          - "8000:80"
        depends_on:
          - notesdb
        extra_hosts:
          - "host.docker.internal:host-gateway"

# The `volumes` tag allows us to share a folder with our container.
# Its syntax is as follows: [folder path on our machine]:[folder path to retrieve in the container]
#volumes:
  # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path.
  # It means that every time the repository is modifying the data inside
  # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`.
  # You don't need to create the `db-data` folder. Docker Compose will do it for you.
#  - ./db-data/:/var/lib/postgresql/data/
    